apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
      protocol: TCP
